#!/bin/bash
set -ex

# Install Homebrew
#/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
# Following Brew's instructions
#echo 'eval $(/home/jovyan/.linuxbrew/bin/brew shellenv)' >> /home/jovyan/.profile
#eval $(/home/jovyan/.linuxbrew/bin/brew shellenv)
#brew tap linuxbrew/xorg
#brew install gcc
# Let's install rust
#brew install rustup
#rustup-init
# Use Brew to install NuShell
#brew install nushell

#curl https://sh.rustup.rs -sSf | sh -- -y
curl https://sh.rustup.rs -sSf > ~/rustup-init.sh
chmod +x ~/rustup-init.sh
~/rustup-init.sh -y
source $HOME/.cargo/env
# Rustup
rustc --version
# Install NuShell with Cargo
cargo install nu --features=stable
# Install NuShell kernelspec
jupyter kernelspec install ../nu_jupyter --user